title: Alan Kan's CV
url: "https://ankitsultana.com"
baseurl: "/markdown-resume"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-133196843-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/markdown-resume/"
 - name: "Download Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Hobbies"
   link: "hobbies"
